baseurl: "./"
title: "RO-MAN 2025 Workshop: RAS4RASM"
canonifyurls: true
theme: "hugo-conference"

GoogleAnalytics: ""

params:
  # Conference info
  Name: "RO-MAN 2025 WS: RAS4RASM (Robots and Autonomous Systems for Refugees, Asylum Seekers, and Migrants)"
  Title: "RAS4RASM"
  Subtitle: "Robots and Autonomous Systems for Refugees, Asylum Seekers, and Migrants"
  Description: ""
  Date: "25 August 2025"
  Venue: "Half-day workshop at RO-MAN 2025"
  Address: "IEEE International Conference on Robot and Human Interactive Communication (RO-MAN 2025)"
  City:  "Eindhoven"
  State: "The Netherlands"
#  Images: ["/img/badge.jpg"]
  GoogleMapsKey: "my-secret-maps-key"

  # Active sections on the website to deactivate comment out with '#'
  # you can also change order here and it will reflect on page
  Sections:
    - about
    #- location
    #- frontiers
    - cfp
    - speakers
    #- papers
    - schedule
    - organizers
    #- sponsors
    #- contact
    #- resources
    #- partners

  # Titles which you can translate to other languages
  Titles:
    about: "Scope"
    cfp: "Call For Papers"
    frontiers: "Special Issue"
    speakers: "Invited speakers"
    papers: "Accepted papers"
    location: "Location"
    schedule: "Schedule"
    organizers: "Organizers"
    partners: "TC Support"
    sponsors: "Project Support"
    contact: "Contact"
    resources: "Resources"

#  # The Call To Action button at the header,
#  # If you don't want this, just remove the callToAction property.
#  CallToAction:
#    text: "Register now!"
#    link: "http://register.example.com"

#  # Fork me on GitHub, if you don't want this, just remove the forkButton property
#  ForkButton:
#    repository: "https://github.com/jweslley/hugo-conference/"

  # List of Sponsors
  Sponsors:
    - name: "AI-CARING"
      logo: "/img/ai-caring-logo-300x154.png"
      url: ""
    - name: "RAEng UK IC Postdoctoral Research Fellowship: Plan and Goal Reasoning for Explainable Autonomous Robots"
      logo: "/img/RExAR.png"
      url: ""
    - name: "COHERENT: COllaborative HiErarchical Robotic ExplaNaTions (CHIST-ERA)"
      logo: "/img/COHERENT.png"
      url: ""
    - name: "aerostream: Strengthening Research and Innovation Excellence in Autonomous Aerial Systems"
      logo: "/img/aerostream.jpg"
      url: "https://aerostream.fer.hr/aerostream"
    - name: "TrustAT - Trustworthy Ad Hoc Teamwork (reference FA9550-22-1-0475)"
      logo: ""
      url: ""
    - name: "Artificial Intelligence Journal"
      logo: "/img/ARTINT_Logo2_c_web_more.jpg"
      url: "https://aij.ijcai.org/funding-opportunities-for-promoting-ai-research/"

  # List of Partners
  Partners:
    - name: "IEEE Technical Committee on Cognitive Robotics"
      url: "https://www.ieee-ras.org/cognitive-robotics"
    - name: "IEEE Technical Committee on Robot Learning"
      url: "https://www.ieee-ras.org/robot-learning"
    - name: "IEEE Technical Committee for on Human-Robot, Interaction & Coordination"
      url: "https://www.ieee-ras.org/human-robot-interaction-coordination"

  # List of Organizers
  Organizers:
    - name: "Shaul Ashkenazi (Corresponding organizer)"
      photo: "/img/shaul.png"
      bio: "University of Glasgow, UK"
      link:
        href: "http://shaulashkenazi.com"
        text: "www"
    - name: "Martim Brandao"
      photo: "/img/martim.jpeg"
      bio: "King's College London, UK"
      link:
        href: "https://www.martimbrandao.com/"
        text: "www"
    - name: "Mary Ellen Foster"
      photo: "/img/maryellen.jpg"
      bio: "University of Glasgow, UK"
      link:
        href: "https://www.maryellenfoster.uk/"
        text: "www"
    - name: "Masoumeh Mansouri"
      photo: "/img/iran.jpg"
      bio: "University of Birmingham, UK"
      link:
        href: "https://iranmansoori.github.io/"
        text: "www"
    - name: "Jane Stuart-Smith"
      photo: "/img/jane.png"
      bio: "University of Glasgow, UK"
      link:
        href: "https://www.gla.ac.uk/schools/critical/staff/janestuart-smith/"
        text: "www"
    - name: "Tom Williams"
      photo: "/img/tom.jpg"
      bio: "Colorado School of Mines, US"
      link:
        href: "https://mirrorlab.mines.edu/"
        text: "www"

  # The entire schedule
  Schedule:

    - name: "Overview of the field of RAS4RASM"
      time: "9:00 - 9:30"

    - name: "Koen Leurs"
      company: "Utrecht University, the Netherlands"
      bio: "Koen Leurs is an associate professor in Gender, Media and Migration Studies at the Graduate Gender Program, Department of Media and Culture, Utrecht University, the Netherlands. His research interests are migration, borders, youth culture and digital technologies, co-creative methodologies and ethics. Currently, Leurs is part of the Management Committee of the Cost-Action DATA-MIG CA22135 - Data Matters: Sociotechnical Challenges of European Migration and Border Control. Recently, Leurs was the PI of the Team Science project Co-designing a fair digital asylum procedure, funded by the Digital Society (‘DiSa’) programme (a research programme by all fourteen Dutch research universities) and COMMIT/, a public-private ICT research community. He recently co-edited Doing Digital Migration Studies (Amsterdam University Press, 2024) and the Handbook of Media and Migration (Sage, 2020) and published the monograph Digital Migration (Sage, 2023)."
      photo: "/img/koen.jpg"
      link:
        href: "https://www.uu.nl/staff/KHALeurs"
        text: "www"
      presentation:
        title: "Doing digital migration studies: pluralizing understandings"
        time: "9:30 - 10:10"
        description: "Digital migration studies refers to an emerging interdisciplinary research area concerned with the study of migration in relation to digital technologies and datafication. In contemporary discussions on migration, digital technology is often considered as a ‘smart’ disruptive tool used by governments to surveill and protect borders while monitoring the movement of people in more efficient ways. However, the story about is more complex. Contemporary migration increasingly reflects a digitally mediated state of migrant being and a digitized and datafied condition. Migration and technology can be said to co-shape one another: migration is a site of technological innovation, and migration is deeply digitally mediated. Koen Leurs, in his recent book Digital Migration (Sage, 2023), and open access volume Doing digital migration studies (co-edited with Sandra Ponzanesi, Amsterdam University Press, 2024) draws out the complex, multilayered relationship between migration and digital technologies. Using an inter-disciplinary approach and covering case studies from the Global North as well as the Global South, Koen Leurs seeks to draw out the contradictions, tensions and hopes that characterize digital migration dynamics. From the critical role that digital infrastructures play in migration management to migrants’ use of devices, platforms and networks to connect and thrive, from the power of digital representations of migrants (and how these can be contested), pre-digital histories to the emotional realities of transnational families, Leurs invites scholars to pluralize understandings of migration and mobility in our contemporary world. In this talk he will draw out digital migration by addressing ontological, epistemological, methodological and ethical dimensions."

    - name: "Dina Sabie"
      company: "Humber College, Canada"
      bio: "Dr. Dina Sabie is a Professor at Humber Polytechnic in Canada. Her research investigates how design, digital technologies, and co-creative practices can support the emotional well-being of migrants. She has worked closely with immigrants, refugees, and internally displaced persons (IDPs), with projects spanning multiple international sites, particularly in Canada and Iraq."
      photo: "/img/dina2.jpg"
      link:
        href: "https://www.cs.toronto.edu/~dsabie/"
        text: "www"
      presentation:
        title: "Beyond Access: Rethinking HCI for Migrants"
        time: "10:10 - 10:25"
        description: "Human-Computer Interaction (HCI) research has increasingly engaged with the technological experiences of refugees and immigrants. Yet, much of this work has traditionally focused on access and service delivery, often overlooking the broader social, emotional, and cultural dimensions of migration. This talk presents insights from research projects conducted in Canada and Iraq that examine how technology can support migrants’ cultural identity, emotional well-being, and social infrastructures. It also highlights critical ethical and political considerations for researchers working at the intersection of technology and [in]voluntary displacement."

    - name: "Yue Hu"
      company: "University of Waterloo, Canada"
      bio: "Yue Hu is an Assistant Professor in Mechanical and Mechatronics Engineering at the University of Waterloo and director of the Active and Interactive Robotics Lab (AIRLab). She holds a PhD in Computer Science from Heidelberg University, with postdoctoral training at Heidelberg and the Italian Institute of Technology (IIT). Prior to joining Waterloo, she held academic and research positions in Japan, including as a JSPS fellow at AIST and Assistant Professor at Tokyo University of Agriculture and Technology. Her research bridges physical-social human-robot interaction, investigating how robots can interact safely and meaningfully with people, working on collaborative robots, humanoid robots, and optimal control, with a recent interest in cybersecurity and privacy in robotic systems. Yue is one of the co-chairs of the IEEE-RAS Technical Committee on Model-based Optimization for Robotics, an Associate Vice-President of the IEEE-RAS Members Activities Board (MAB), and an advisor for the organization Women in AI & Robotics."
      photo: "/img/yue.jpg"
      link:
        href: "https://uwaterloo.ca/active-and-interactive-robotics-lab/"
        text: "www"
      presentation:
        title: "Designing Peer-Learner Robots for Language Learning in Refugee Resettlement Contexts"
        time: "10:25 - 10:40"
        description: "Language acquisition is a critical factor in the successful integration of refugees and asylum seekers, yet existing educational supports are often limited in accessibility and personalization. This talk presents early-stage research on the design of peer-learner social robots for supporting language learning among refugee and immigrant families. As part of a broader effort to develop inclusive and responsive human-robot interaction (HRI), we explore how the social role of a robot might shape engagement and interaction in robot-assisted language learning (RALL). Early evaluations and engagement with frontline service providers highlight key design considerations around role framing, responsiveness, and social presence. Building on this foundation, the work is progressing toward community-partnered development and deployment in real-world newcomer support settings. The talk reflects on methodological challenges and future directions for inclusive, context-aware human-robot interaction in migration and resettlement domains."

    - name: "Coffee break"
      time: "10:40 - 11:00"

    - name: "Short presentations (Accepted papers)"
      time: "11:00 - 11:40"

    - name: "Panel/Group discussion"
      time: "11:40 - 12:15"

    - name: "Closing remarks"
      time: "12:15 - 12:30"

    #- name: "Session 1: Responsible robotics and societal impact"
    #  separator: ""

    #- name: "Opening (organizers)"
    #  time: "10:15 - 10:30"

    #- name: "Alan Winfield"
    #  photo: "/img/alan.jpg"
    #  bio: ""
    #  company: "University of West of England"
    #  link:
    #    href: "http://alanwinfield.blogspot.com/"
    #    text: "www"
    #  presentation:
    #    title: "Robot Accident Investigation: a case study in Responsible Robotics"
    #    description: "Description"
    #    time: "10:30 - 11:00"
    #  video: "https://youtu.be/mjGW52_BvPc"


